// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAjo-shDw7RBCZ4E7E4OX72_QxzRXqGtM',
    appId: '1:164393524281:web:4fa72aa17e06e176b581e8',
    messagingSenderId: '164393524281',
    projectId: 'task-c6f50',
    authDomain: 'task-c6f50.firebaseapp.com',
    storageBucket: 'task-c6f50.firebasestorage.app',
    measurementId: 'G-3GKJT2MJ36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBIfnn6mxjeepK0pVdXcpChEHCn-9MG5Y',
    appId: '1:164393524281:android:9d203947d1a6dda3b581e8',
    messagingSenderId: '164393524281',
    projectId: 'task-c6f50',
    storageBucket: 'task-c6f50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvBZaYl281QrrIMH39ylx45AyOdUtzq3I',
    appId: '1:164393524281:ios:fa13f04428b1d50fb581e8',
    messagingSenderId: '164393524281',
    projectId: 'task-c6f50',
    storageBucket: 'task-c6f50.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvBZaYl281QrrIMH39ylx45AyOdUtzq3I',
    appId: '1:164393524281:ios:fa13f04428b1d50fb581e8',
    messagingSenderId: '164393524281',
    projectId: 'task-c6f50',
    storageBucket: 'task-c6f50.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAjo-shDw7RBCZ4E7E4OX72_QxzRXqGtM',
    appId: '1:164393524281:web:70ee96cff4cfc0a1b581e8',
    messagingSenderId: '164393524281',
    projectId: 'task-c6f50',
    authDomain: 'task-c6f50.firebaseapp.com',
    storageBucket: 'task-c6f50.firebasestorage.app',
    measurementId: 'G-S62Y10RM07',
  );

}