// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsh6fl7zZ1N_8dUdJJAA2bFif4C5nDs48',
    appId: '1:222699679481:web:1176bb05cd2473b7447c28',
    messagingSenderId: '222699679481',
    projectId: 'taskmanager-a86db',
    authDomain: 'taskmanager-a86db.firebaseapp.com',
    storageBucket: 'taskmanager-a86db.firebasestorage.app',
    measurementId: 'G-7H59N8K3J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrZqsazG8Oz0QPUvGN7EsusbGyLoH7K0E',
    appId: '1:222699679481:android:0ea01a3db04a8ed6447c28',
    messagingSenderId: '222699679481',
    projectId: 'taskmanager-a86db',
    storageBucket: 'taskmanager-a86db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKWeRmPa1DmthLJ2JSWitmspOCd6JMJYI',
    appId: '1:222699679481:ios:53cb892c91f89fc9447c28',
    messagingSenderId: '222699679481',
    projectId: 'taskmanager-a86db',
    storageBucket: 'taskmanager-a86db.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKWeRmPa1DmthLJ2JSWitmspOCd6JMJYI',
    appId: '1:222699679481:ios:53cb892c91f89fc9447c28',
    messagingSenderId: '222699679481',
    projectId: 'taskmanager-a86db',
    storageBucket: 'taskmanager-a86db.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsh6fl7zZ1N_8dUdJJAA2bFif4C5nDs48',
    appId: '1:222699679481:web:19c527cf3b1a1b68447c28',
    messagingSenderId: '222699679481',
    projectId: 'taskmanager-a86db',
    authDomain: 'taskmanager-a86db.firebaseapp.com',
    storageBucket: 'taskmanager-a86db.firebasestorage.app',
    measurementId: 'G-ZSLVKBJ5BJ',
  );
}
